version: "3.6"
services:
    rabbitmq:
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password        
        image: rabbitmq:3-management
                
    customerapi:
        container_name: customerapi
        ports:
            - 8000:80
            - 8001:443
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=8001
            - ASPNETCORE_Kestrel__Certificates__Default__Password=password
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ${USERPROFILE}\.aspnet\https:/https/      
        build:
            context: ./CustomerApi
            dockerfile: CustomerApi/Dockerfile      
        depends_on:
            - rabbitmq
        
    orderapi:
        container_name: order
        ports:
            - 9000:80
            - 9001:443
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=9001
            - ASPNETCORE_Kestrel__Certificates__Default__Password=password
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx 
        volumes:
            - ${USERPROFILE}\.aspnet\https:/https/     
        build:
            context: ./OrderApi      
            dockerfile: OrderApi/Dockerfile
        depends_on:
            - rabbitmq 